# Importar as bibliotecas

In [1]:
import pandas as pd
import numpy as np

A tabela do problema foi salva como um arquivo csv que é lido e salvo na variável 'data' na linha abaixo

In [2]:
data = pd.read_csv('Amostras_solo.txt')

## Funções utilizadas

In [3]:
def mining(data):
    length = data.shape[1]
    X = []
    columns = data.columns
    for i in range(length):
        X.append(list(data[columns[i]]))
    return X

def estatistica(param):
    media = np.mean(param)
    mediana = np.median(param)
    desvio = np.std(param)
    maxi = np.max(param)
    mini = np.min(param)
    return media, mediana, desvio, maxi, mini

def cov_M(params):
    M = np.matrix(params)
    cov = np.matrix(np.cov(M))
    return cov, M

Abaixo, o código utilizado para gerar uma tebela com os parâmetros: Média, mediana, desvio, valor máximo (max) e valor mínimo (min).

In [4]:
params = mining(data) #lista que pode ser uma matrix 4x24
est = {}
columns = data.columns
for i in range(data.shape[1]):
    c = columns[i].split('(')[0]
    est[c] = list(estatistica(params[i]))
index = ['media', 'mediana', 'desvio', 'max', 'min']
estFrame = pd.DataFrame(est, index = index)
print(estFrame)

             Areia     Argila  Mat. Organ  Sedimentos
media    67.779167  10.195833    2.833333   22.108333
mediana  67.450000  10.150000    2.850000   22.900000
desvio    8.085789   3.032529    0.810692    6.182699
max      83.700000  17.600000    4.400000   32.800000
min      55.900000   5.800000    0.900000   10.500000


A matriz de covariância é calculada abaixo: 

In [5]:
cov, M = cov_M(params)
print("Matriz de covariancia")
print(cov)

Matriz de covariancia
[[ 6.82225906e+01 -4.89132971e+01 -1.83770471e+01  1.79855072e+00]
 [-4.89132971e+01  3.98877536e+01  8.52047101e+00 -1.81420290e+00]
 [-1.83770471e+01  8.52047101e+00  9.59606884e+00 -1.33333333e-02]
 [ 1.79855072e+00 -1.81420290e+00 -1.33333333e-02  6.85797101e-01]]


Os autovalores e autovetores são calculados utilizando o numpy, como é mostrado abaixo

In [6]:
autovalor, autovetor = np.linalg.eig(cov)
print('autovalor')
print(autovalor)

print('autovetor')
print(autovetor)

autovalor
[1.08992777e+02 8.76606779e+00 5.01274801e-02 5.83237986e-01]
autovetor
[[-0.78838911  0.22921536 -0.5701868  -0.02810589]
 [ 0.58276295  0.57071056 -0.57778339  0.02903718]
 [ 0.1957206  -0.78485716 -0.58202768 -0.08328544]
 [-0.02287773 -0.07582228 -0.04792865  0.995706  ]]


In [7]:
val = list(autovalor)
val.reverse()
print('Autovalores em ordem decrescente')
print(val)

Autovalores em ordem decrescente
[0.5832379864395187, 0.0501274800752674, 8.766067786898015, 108.99277689151481]


O traço da matriz de covariância é igual a soma dos autovalores

In [8]:
print('Traço da matriz de covariância')
print(np.trace(cov))

print('Soma de todos os autovalores')
print(sum(autovalor))


Traço da matriz de covariância
118.39221014492753
Soma de todos os autovalores
118.3922101449276


A equação dos componentes principais é mostrada a seguir:

In [9]:
print('Y = ' + str(autovetor[:,0].T) + 'X1' + ' + ' + str(autovetor[:,1].T) + 'X2' + 
      str(autovetor[:,2].T) + 'X3' + ' + ' + str(autovetor[:,3].T) + 'X4')

Y = [[-0.78838911  0.58276295  0.1957206  -0.02287773]]X1 + [[ 0.22921536  0.57071056 -0.78485716 -0.07582228]]X2[[-0.5701868  -0.57778339 -0.58202768 -0.04792865]]X3 + [[-0.02810589  0.02903718 -0.08328544  0.995706  ]]X4


O percentual de variância é obtido com o trecho de código abaixo

In [10]:
autoval = []
var = sum(autovalor)
for i in range(len(autovalor)):
    autoval.append(autovalor[i]/var)

print(autoval)

[0.9206076713838972, 0.07404260614923226, 0.0004234018438705113, 0.004926320623000102]


Sendo assim, de acordo com a sequência dos dados da tabela inicial, os componentes mais importantes em ordem decrescente são: Areia, sedimentos, matéria orgânica e argila